export const DESIGNERS = [
  {
    name: 'Lynn',
    verified: true,
    rating: '4.9',
    bio: '由礦物紋理與佩戴場景出發，做令人記得住的手鏈。',
    works: '3',
    income: 'HK$ 5.2萬',
    avatar: './home/designer-avatar.png',
  },
  {
    name: '林予',
    verified: true,
    rating: '4.8',
    bio: '偏愛冷色石英與金屬間隔，強調留白與節奏。',
    works: '3',
    income: 'HK$ 3.6萬',
    avatar: './home/designer-avatar-2.png',
  },
  {
    name: 'Ada',
    verified: true,
    rating: '4.9',
    bio: '愛用檸檬晶、薰衣草和青提這類明亮石頭，做輕盈的日間手鏈。',
    works: '4',
    income: 'HK$ 4.1萬',
    avatar: './home/designer-avatar-3.png',
  },
]

/** Sum of bead diameters in cm. Inspiration works must be at least 13. */
export function recipeWristCm(recipe) {
  return recipe.reduce((sum, item) => sum + (item.diameter || 8) * (item.count || 1), 0) / 10
}

export const WORKS = [
  {
    id: 'lynn-amethyst',
    designer: 'Lynn',
    title: '紫晶安神',
    desc: '烏拉圭紫晶滿串，白水晶點睛，日常安神助眠的熱賣款。',
    recipe: [
      { name: '烏拉圭紫水晶', diameter: 8, count: 5 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '烏拉圭紫水晶', diameter: 8, count: 5 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '烏拉圭紫水晶', diameter: 8, count: 5 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
    ],
  },
  {
    id: 'lynn-strawberry',
    designer: 'Lynn',
    title: '草莓招桃',
    desc: '淺草莓晶配粉晶，溫柔招桃花，是閨蜜禮盒裏最常被揀的一串。',
    recipe: [
      { name: '淺草莓晶', diameter: 8, count: 4 },
      { name: '粉晶', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '淺草莓晶', diameter: 8, count: 4 },
      { name: '粉晶', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '淺草莓晶', diameter: 8, count: 4 },
      { name: '粉晶', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
    ],
  },
  {
    id: 'lynn-nanhong',
    designer: 'Lynn',
    title: '南紅聚財',
    desc: '南紅瑪瑙配太陽石與蜜蠟桶珠，暖色開運，今季店舖回購最高。',
    recipe: [
      { name: '南紅瑪瑙', diameter: 8, count: 4 },
      { name: '太陽石', diameter: 8, count: 1 },
      { name: '蜜蠟桶珠', diameter: 8, count: 1 },
      { name: '南紅瑪瑙', diameter: 8, count: 4 },
      { name: '太陽石', diameter: 8, count: 1 },
      { name: '蜜蠟桶珠', diameter: 8, count: 1 },
      { name: '南紅瑪瑙', diameter: 8, count: 4 },
      { name: '太陽石', diameter: 8, count: 1 },
      { name: '蜜蠟桶珠', diameter: 8, count: 1 },
    ],
  },
  {
    id: 'linyu-aqua',
    designer: '林予',
    title: '海藍靜語',
    desc: '冰川藍海藍寶與月光石留白，冷色清爽，返工和約會都合適。',
    recipe: [
      { name: '冰川藍海藍寶', diameter: 8, count: 4 },
      { name: '月光石', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '冰川藍海藍寶', diameter: 8, count: 4 },
      { name: '月光石', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '冰川藍海藍寶', diameter: 8, count: 4 },
      { name: '月光石', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
    ],
  },
  {
    id: 'linyu-obsidian',
    designer: '林予',
    title: '金曜守界',
    desc: '雙眼金曜石配冰曜與灰月光，防小人、壓氣場的經典男款也有女生在戴。',
    recipe: [
      { name: '雙眼金曜石', diameter: 8, count: 5 },
      { name: '高透冰曜石', diameter: 8, count: 1 },
      { name: '雙眼金曜石', diameter: 8, count: 5 },
      { name: '透體灰月光', diameter: 8, count: 1 },
      { name: '雙眼金曜石', diameter: 8, count: 4 },
      { name: '高透冰曜石', diameter: 8, count: 1 },
      { name: '透體灰月光', diameter: 8, count: 1 },
    ],
  },
  {
    id: 'linyu-phantom',
    designer: '林予',
    title: '幽靈森綠',
    desc: '綠幽靈與千層綠層層疊透，中間點白水晶，事業運與清新感一齊做。',
    recipe: [
      { name: '綠幽靈', diameter: 8, count: 4 },
      { name: '千層綠', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '綠幽靈', diameter: 8, count: 4 },
      { name: '千層綠', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '綠幽靈', diameter: 8, count: 4 },
      { name: '千層綠', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
    ],
  },
  {
    id: 'ada-lemon',
    designer: 'Ada',
    title: '檸香午後',
    desc: '檸檬黃水晶配菠蘿切面檸檬晶，白水晶透氣，夏天手腕上最顯精神的一串。',
    recipe: [
      { name: '檸檬黃水晶', diameter: 8, count: 4 },
      { name: '檸檬晶菠蘿', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '檸檬黃水晶', diameter: 8, count: 4 },
      { name: '檸檬晶菠蘿', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '檸檬黃水晶', diameter: 8, count: 4 },
      { name: '檸檬晶菠蘿', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
    ],
  },
  {
    id: 'ada-lavender',
    designer: 'Ada',
    title: '薰衣草信',
    desc: '薰衣草圓珠與方糖交替，淡紫色像一封寫給自己的短箋，返工或臨睡前都適合。',
    recipe: [
      { name: '薰衣草', diameter: 8, count: 4 },
      { name: '薰衣草方糖', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '薰衣草', diameter: 8, count: 4 },
      { name: '薰衣草方糖', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '薰衣草', diameter: 8, count: 4 },
      { name: '薰衣草方糖', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
    ],
  },
  {
    id: 'ada-sun',
    designer: 'Ada',
    title: '金陽開運',
    desc: '金太陽配高透黃水晶和黃螢石，亮色聚財又不沉，是她工作室裏回購最多的日間款。',
    recipe: [
      { name: '金太陽', diameter: 8, count: 4 },
      { name: '高透黃水晶', diameter: 8, count: 1 },
      { name: '黃螢石', diameter: 8, count: 1 },
      { name: '金太陽', diameter: 8, count: 4 },
      { name: '高透黃水晶', diameter: 8, count: 1 },
      { name: '黃螢石', diameter: 8, count: 1 },
      { name: '金太陽', diameter: 8, count: 4 },
      { name: '高透黃水晶', diameter: 8, count: 1 },
      { name: '黃螢石', diameter: 8, count: 1 },
    ],
  },
  {
    id: 'ada-grape',
    designer: 'Ada',
    title: '青提初夏',
    desc: '葡萄石與青提石疊出果綠，白水晶留白，像剛切開的一盤水果，輕、乾淨。',
    recipe: [
      { name: '葡萄石', diameter: 8, count: 4 },
      { name: '青提', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '葡萄石', diameter: 8, count: 4 },
      { name: '青提', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
      { name: '葡萄石', diameter: 8, count: 4 },
      { name: '青提', diameter: 8, count: 1 },
      { name: '淨體白水晶', diameter: 8, count: 1 },
    ],
  },
].filter((work) => recipeWristCm(work.recipe) >= 13)
